'use strict';
export const Checksum = {
    HEADER: 0x3e,
    TRAILER: 0x3c,
    ESCAPE: 0x3d,
    ESCAPE_MASK: 0xef,
};

export const MessageType = {
    ACK: 0x01,
    COMMAND_1: 0x0c,
    COMMAND_2: 0x0e,
    UNKNOWN: 0xff,
};

export const SonyConfiguration = [
    {
        name: 'LinkBuds',
        pattern: /^LinkBuds$/,
        modaliasPrefix: 'v054Cp0DDF',
        batteryDual: true,
        batteryCase: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        adaptiveVolumeControl: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        wideAreaTap: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds-wingtip',
        budsIcon: 'earbuds-wingtip',
        case: 'case-normal',
    },
    {
        name: 'LinkBuds S',
        pattern: /.*LinkBuds S.*/,
        modaliasPrefix: 'v054Cp0DF4',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        ambientSoundControlButtonMode: true,
        quickAccess: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        powerOffFromPhone: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        voiceNotifications: true,
        equalizerSixBands: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-1000XM3', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM3.*/,
        modaliasPrefix: 'v054Cp0CE0',
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds2',
        budsIcon: 'earbuds2',
        case: 'case-normal',
    },
    {
        name: 'WF-1000XM4', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM4.*/,
        modaliasPrefix: 'v054Cp0DE1',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-1000XM5', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM5.*/,
        modaliasPrefix: 'v054Cp0E63',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-C500',
        pattern: /.*WF-C500.*/,
        batteryDual: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C510',
        pattern: /.*WF-C510.*/,
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        noNoiseCancelling: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C700N',   // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-C700N.*/,
        modaliasPrefix: 'v054Cp0EC4',
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C710N',
        pattern: /.*WF-C710N.*/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-SP800N',
        pattern: /.*WF-SP800N.*/,
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        equalizerSixBands: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'earbuds-wingtip',
        budsIcon: 'earbuds-wingtip',
        case: 'case-oval-short',
    },
    {
        name: 'WH-1000XM2',
        pattern: /.*WH-1000XM2.*/,
        modaliasPrefix: 'v054Cp0C67',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerSixBands: true,
        soundPosition: true,
        surroundMode: true,
        audioUpsampling: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM3', // uuid: 96cc203e-5068-46ad-b32d-e316f5e069ba (v1)
        pattern: /.*WH-1000XM3.*/,
        modaliasPrefix: 'v054Cp0CD3',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        automaticPowerOffByTime: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM4', // uuid: 96cc203e-5068-46ad-b32d-e316f5e069ba (v1)
        pattern: /.*WH-1000XM4.*/,
        modaliasPrefix: 'v054Cp0D58',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        ancOptimizer: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM5', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WH-1000XM5.*/,
        modaliasPrefix: 'v054Cp0DF0',
        batterySingle: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        equalizerSixBands: true,
        quickAccess: true,
        pauseWhenTakenOff: true,
        audioUpsampling: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM6', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WH-1000XM6.*/,
        modaliasPrefix: 'v054Cp0F8A',
        batterySingle: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        ambientSoundControlNA: true,
        ambientSoundControlButtonMode: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        equalizerTenBands: true,
        listeningMode: true,
        quickAccess: true,
        audioUpsampling: true,
        pauseWhenTakenOff: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'Sony ULT',
        pattern: /^(Sony ULT|ULT WEAR)$/,
        batterySingle: true,
        ambientSoundControl: true,
        powerOffFromPhone: true,
        pauseWhenTakenOff: true,
        quickAccess: true,
        voiceNotifications: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-XB910N',
        pattern: /.*WH-XB910N.*/,
        batterySingle: true,
        ambientSoundControl: true,
        powerOffFromPhone: true,
        pauseWhenTakenOff: true,
        quickAccess: true,
        equalizerSixBands: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WI-C100',
        pattern: /.*WI-C100.*/,
        batterySingle: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds-neckband',
        budsIcon: 'earbuds-neckband',
    },
    {
        name: 'WI-SP600N',
        pattern: /.*WI-SP600N.*/,
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        soundPosition: true,
        surroundMode: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        volume: true,
        albumArtIcon: 'earbuds-neckband',
        budsIcon: 'earbuds-neckband',
    },
];

export function booleanFromByte(val) {
    switch (val) {
        case 0x00:
            return false;
        case 0x01:
            return true;
        default:
            return null;
    }
}

export function isValidByte(val, enumObj) {
    return Object.values(enumObj).includes(val);
}
