'use strict';
export const checksum = {
    HEADER: 0x3e,
    TRAILER: 0x3c,
    ESCAPE: 0x3d,
    ESCAPE_MASK: 0xef,
};

export const MessageType = {
    ACK: 0x01,
    COMMAND_1: 0x0c,
    COMMAND_2: 0x0e,
    UNKNOWN: 0xff,
};

export const PayloadType = {
    INIT_REQUEST: 0x00,
    INIT_REPLY: 0x01,

    BATTERY_LEVEL_REQUEST: 0x10,
    BATTERY_LEVEL_REPLY: 0x11,
    BATTERY_LEVEL_NOTIFY: 0x13,

    BATTERY_LEVEL_REQUEST_V2: 0x22,
    BATTERY_LEVEL_REPLY_V2: 0x23,
    BATTERY_LEVEL_NOTIFY_V2: 0x25,

    AMBIENT_SOUND_CONTROL_GET: 0x66,
    AMBIENT_SOUND_CONTROL_SET: 0x68,
    AMBIENT_SOUND_CONTROL_RET: 0x67,
    AMBIENT_SOUND_CONTROL_NOTIFY: 0x69,

    AUTOMATIC_POWER_OFF_BUTTON_MODE_GET: 0xF6,
    AUTOMATIC_POWER_OFF_BUTTON_MODE_RET: 0xF7,
    AUTOMATIC_POWER_OFF_BUTTON_MODE_SET: 0xF8,
    AUTOMATIC_POWER_OFF_BUTTON_MODE_NOTIFY: 0xF9,

    // v2
    AUTOMATIC_POWER_OFF_GET: 0x26,
    AUTOMATIC_POWER_OFF_RET: 0x27,
    AUTOMATIC_POWER_OFF_SET: 0x28,
    AUTOMATIC_POWER_OFF_NOTIFY: 0x29,

    SPEAK_TO_CHAT_CONFIG_GET: 0xFA,
    SPEAK_TO_CHAT_CONFIG_SET: 0xFC,
    SPEAK_TO_CHAT_CONFIG_RET: 0xFB,
    SPEAK_TO_CHAT_CONFIG_NOTIFY: 0xFD,

    PLAYBACK_STATUS_GET: 0xA6,
    PLAYBACK_STATUS_RET: 0xA7,
    PLAYBACK_STATUS_SET: 0xA8,
    PLAYBACK_STATUS_NOTIFY: 0xA9,

    EQUALIZER_GET: 0x56,
    EQUALIZER_RET: 0x57,
    EQUALIZER_SET: 0x58,
    EQUALIZER_NOTIFY: 0x59,

    VOICE_NOTIFICATIONS_GET: 0x46,
    VOICE_NOTIFICATIONS_RET: 0x47,
    VOICE_NOTIFICATIONS_SET: 0x48,
    VOICE_NOTIFICATIONS_NOTIFY: 0x49,

    AUDIO_PARAM_GET: 0xE6,
    AUDIO_PARAM_RET: 0xE7,
    AUDIO_PARAM_SET: 0xE8,
    AUDIO_PARAM_NOTIFY: 0xE9,
};

export const BatteryTypeV1 = {
    SINGLE: 0x00,
    DUAL: 0x01,
    CASE: 0x02,
};

export const BatteryTypeV2 = {
    SINGLE: 0x00,
    DUAL: 0x01,
    DUAL2: 0x09,
    CASE: 0x0a,
};

export const AmbientSoundMode = {
    ANC_OFF: 0,
    ANC_ON: 1,
    WIND: 2,
    AMBIENT: 3,
};

export const AutoAsmSensitivity = {
    STANDARD: 0,
    HIGH: 1,
    LOW: 2,
};

export const Speak2ChatSensitivity = {
    AUTO: 0x00,
    HIGH: 0x01,
    LOW: 0x02,
};

export const Speak2ChatTimeout = {
    SHORT: 0x00,
    STANDARD: 0x01,
    LONG: 0x02,
    OFF: 0x03,
};

export const PlaybackStatus = {
    PLAY: 0x01,
    PAUSE: 0x02,
};

export const EqualizerPreset = {
    OFF: 0x00,
    BRIGHT: 0x10,
    EXCITED: 0x11,
    MELLOW: 0x12,
    RELAXED: 0x13,
    VOCAL: 0x14,
    TREBLE_BOOST: 0x15,
    BASS_BOOST: 0x16,
    SPEECH: 0x17,
    MANUAL: 0xa0,
    CUSTOM_1: 0xa1,
    CUSTOM_2: 0xa2,
};

export const ListeningMode = {
    CINEMA: 0x00,
    STANDARD: 0x01,
    BGM: 0x02, // Should not be sent
};

export const BgmDistance = {
    MY_ROOM: 0x00,
    LIVING_ROOM: 0x01,
    CAFE: 0x02,
};

export const AutoPowerOff = {
    OFF: {id: 0, bytes: [0x11, 0x00]},
    AFTER_5_MIN: {id: 1, bytes: [0x00, 0x00]},
    AFTER_30_MIN: {id: 2, bytes: [0x01, 0x01]},
    AFTER_1_HOUR: {id: 3, bytes: [0x02, 0x02]},
    AFTER_3_HOUR: {id: 4, bytes: [0x03, 0x03]},
    WHEN_TAKEN_OFF: {id: 5, bytes: [0x10, 0x00]},
};


export const SonyConfiguration = [
    {
        name: 'LinkBuds',
        pattern: /^LinkBuds$/,
        modaliasPrefix: 'v054Cp0DDF',
        batteryDual: true,
        batteryCase: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        adaptiveVolumeControl: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        wideAreaTap: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds-wingtip',
        budsIcon: 'earbuds-wingtip',
        case: 'case-normal',
    },
    {
        name: 'LinkBuds S',
        pattern: /.*LinkBuds S.*/,
        modaliasPrefix: 'v054Cp0DF4',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        ambientSoundControlButtonMode: true,
        quickAccess: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        powerOffFromPhone: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        voiceNotifications: true,
        equalizerSixBands: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-1000XM3', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM3.*/,
        modaliasPrefix: 'v054Cp0CE0',
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds2',
        budsIcon: 'earbuds2',
        case: 'case-normal',
    },
    {
        name: 'WF-1000XM4', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM4.*/,
        modaliasPrefix: 'v054Cp0DE1',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-1000XM5', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-1000XM5.*/,
        modaliasPrefix: 'v054Cp0E63',
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval',
    },
    {
        name: 'WF-C500',
        pattern: /.*WF-C500.*/,
        batteryDual2: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C510',
        pattern: /.*WF-C510.*/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        noNoiseCancelling: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C700N',   // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WF-C700N.*/,
        modaliasPrefix: 'v054Cp0EC4',
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-C710N',
        pattern: /.*WF-C710N.*/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds',
        case: 'case-oval-short',
    },
    {
        name: 'WF-SP800N',
        pattern: /.*WF-SP800N.*/,
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        equalizerSixBands: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'earbuds-wingtip',
        budsIcon: 'earbuds-wingtip',
        case: 'case-oval-short',
    },
    {
        name: 'WH-1000XM2',
        pattern: /.*WH-1000XM2.*/,
        modaliasPrefix: 'v054Cp0C67',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerSixBands: true,
        soundPosition: true,
        surroundMode: true,
        audioUpsampling: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM3', // uuid: 96cc203e-5068-46ad-b32d-e316f5e069ba (v1)
        pattern: /.*WH-1000XM3.*/,
        modaliasPrefix: 'v054Cp0CD3',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        automaticPowerOffByTime: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM4', // uuid: 96cc203e-5068-46ad-b32d-e316f5e069ba (v1)
        pattern: /.*WH-1000XM4.*/,
        modaliasPrefix: 'v054Cp0D58',
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        ancOptimizer: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM5', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WH-1000XM5.*/,
        modaliasPrefix: 'v054Cp0DF0',
        batterySingle: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        equalizerSixBands: true,
        quickAccess: true,
        pauseWhenTakenOff: true,
        audioUpsampling: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WH-1000XM6', // uuid: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2 (v2)
        pattern: /.*WH-1000XM6.*/,
        modaliasPrefix: 'v054Cp0F8A',
        batterySingle: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        ambientSoundControlNA: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        equalizerTenBands: true,
        listeningMode: true,
        quickAccess: true,
        audioUpsampling: true,
        pauseWhenTakenOff: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'Sony ULT',
        pattern: /^Sony ULT|ULT WEAR$/,
        batterySingle: true,
        ambientSoundControl: true,
        powerOffFromPhone: true,
        pauseWhenTakenOff: true,
        quickAccess: true,
        voiceNotifications: true,
        albumArtIcon: 'headphone1',
        budsIcon: 'headphone1',
    },
    {
        name: 'WI-C100',
        pattern: /.*WI-C100.*/,
        batterySingle: true,
        equalizerSixBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds-neckband',
        budsIcon: 'earbuds-neckband',
    },
];

