'use strict';
export const checksum = {
    HEADER: 0x3e,
    TRAILER: 0x3c,
    ESCAPE: 0x3d,
    ESCAPE_MASK: 0xef,
};

export const MessageType = {
    ACK: 0x01,
    COMMAND_1: 0x0c,
    COMMAND_2: 0x0e,
    UNKNOWN: 0xff,
};

export const PayloadType = {
    INIT_REQUEST: 0x00,
    INIT_REPLY: 0x01,

    BATTERY_LEVEL_REQUEST: 0x10,
    BATTERY_LEVEL_REPLY: 0x11,
    BATTERY_LEVEL_NOTIFY: 0x13,

    BATTERY_LEVEL_REQUEST_V2: 0x22,
    BATTERY_LEVEL_REPLY_V2: 0x23,
    BATTERY_LEVEL_NOTIFY_V2: 0x25,

    AMBIENT_SOUND_CONTROL_GET: 0x66,
    AMBIENT_SOUND_CONTROL_SET: 0x68,
    AMBIENT_SOUND_CONTROL_RET: 0x67,
    AMBIENT_SOUND_CONTROL_NOTIFY: 0x69,

    SPEAK_TO_CHAT_CONFIG_GET: 0xfa,
    SPEAK_TO_CHAT_CONFIG_SET: 0xfc,
    SPEAK_TO_CHAT_CONFIG_RET: 0xfb,
    SPEAK_TO_CHAT_CONFIG_NOTIFY: 0xfd,

    PLAYBACK_STATUS_GET: 0xa6,
    PLAYBACK_STATUS_RET: 0xa7,
    PLAYBACK_STATUS_SET: 0xa8,
    PLAYBACK_STATUS_NOTIFY: 0xa9,
};

export const BatteryTypeV1 = {
    SINGLE: 0x00,
    DUAL: 0x01,
    CASE: 0x02,
};

export const BatteryTypeV2 = {
    SINGLE: 0x00,
    DUAL: 0x01,
    DUAL2: 0x09,
    CASE: 0x0a,
};

export const AmbientSoundMode = {
    ANC_OFF: 0,
    ANC_ON: 1,
    AMBIENT: 2,
    WIND: 3,
};

export const Speak2ChatSensitivity = {
    AUTO: 0x00,
    HIGH: 0x01,
    LOW: 0x02,
};

export const Speak2ChatTimeout = {
    SHORT: 0x00,
    STANDARD: 0x01,
    LONG: 0x02,
    OFF: 0x03,
};

export const PlaybackStatus = {
    PLAY: 0x01,
    PAUSE: 0x02,
};


export const SonyConfiguration = [
    {
        name: 'LinkBuds',
        pattern: /^LinkBuds$/,
        batteryDual: true,
        batteryCase: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        adaptiveVolumeControl: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        wideAreaTap: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'LinkBuds S',
        pattern: /.*LinkBuds S.*/,
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        ambientSoundControlButtonMode: true,
        quickAccess: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        powerOffFromPhone: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        voiceNotifications: true,
        equalizerWithCustomBands: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-1000XM3',
        pattern: /.*WF-1000XM3.*/,
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-1000XM4',
        pattern: /.*WF-1000XM4.*/,
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSimple: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-1000XM5',
        pattern: /.*WF-1000XM5.*/,
        batteryDual: true,
        batteryCase: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        equalizerSimple: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-C500',
        pattern: /.*WF-C500.*/,
        batteryDual2: true,
        equalizerSimple: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-C510',
        pattern: /WF-C510/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        noNoiseCancelling: true,
        equalizerSimple: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-C700N',
        pattern: /WF-C700N/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        equalizerSimple: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-C710N',
        pattern: /WF-C710N/,
        batteryDual2: true,
        batteryCase: true,
        ambientSoundControl2: true,
        equalizerSimple: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        buttonModesLeftRight: true,
        powerOffFromPhone: true,
        ambientSoundControlButtonMode: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WF-SP800N',
        pattern: /.*WF-SP800N.*/,
        batteryDual: true,
        batteryCase: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        equalizerWithCustomBands: true,
        buttonModesLeftRight: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WH-1000XM2',
        pattern: /.*WH-1000XM2.*/,
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerWithCustomBands: true,
        soundPosition: true,
        surroundMode: true,
        audioUpsampling: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WH-1000XM3',
        pattern: /.*WH-1000XM3.*/,
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        ancOptimizer: true,
        audioSettingsOnlyOnSbcCodec: true,
        equalizerWithCustomBands: true,
        soundPosition: true,
        surroundMode: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        automaticPowerOffByTime: true,
        voiceNotifications: true,
        volume: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WH-1000XM4',
        pattern: /.*WH-1000XM4.*/,
        batterySingle: true,
        ambientSoundControl: true,
        windNoiseReduction: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        ancOptimizer: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        touchSensorSingle: true,
        pauseWhenTakenOff: true,
        automaticPowerOffWhenTakenOff: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WH-1000XM5',
        pattern: /.*WH-1000XM5.*/,
        batterySingle: true,
        powerOffFromPhone: true,
        ambientSoundControl: true,
        speakToChatEnabled: true,
        speakToChatConfig: true,
        speakToChatFocusOnVoice: true,
        voiceNotifications: true,
        automaticPowerOffWhenTakenOff: true,
        equalizerWithCustomBands: true,
        quickAccess: true,
        pauseWhenTakenOff: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'Sony ULT',
        pattern: /^Sony ULT|ULT WEAR$/,
        batterySingle: true,
        ambientSoundControl: true,
        powerOffFromPhone: true,
        pauseWhenTakenOff: true,
        quickAccess: true,
        voiceNotifications: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
    {
        name: 'WI-C100',
        pattern: /.*WI-C100.*/,
        batterySingle: true,
        equalizerSimple: true,
        equalizerWithCustomBands: true,
        audioUpsampling: true,
        voiceNotifications: true,
        powerOffFromPhone: true,
        albumArtIcon: 'earbuds',
        budsIcon: 'earbuds-stem3',
        case: 'case-normal',
    },
];

